### ISSUE TITLE
Can't built on OSX

### ISSUE THREAD

**Issue by sdrib** [openlink/iODBC#1]
I am on OSX 10.8.2. I get this error when I try *Method 1*, as described in the Mac Readme file:
``/bin/sh: build: command not found``

When I try *Method 2:* , I get:
``sh: bootstrap.sh: No such file or directory``

What am I missing? I have the latest Developer Packages.

**Comment by pwagland** [comment]
Two years later, and the Mac directory doesn't build when following the directions <https://github.com/openlink/iODBC/blob/develop/README.MACOSX>.

Method 2, does seem to work, but does not build/install any of the applications.

**Comment by openlink** [comment]
Thanks for reporting. I fixed the problem on the latest develop branch. Please try Method 1 again.

**Comment by pwagland** [comment]
Thanks for the quick response! Sadly, that doesn't work for me:

17:39 $ git clone https://github.com/openlink/iODBC.git
Cloning into 'iODBC'...
remote: Counting objects: 7798, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 7798 (delta 23), reused 0 (delta 0), pack-reused 7739
Receiving objects: 100% (7798/7798), 3.30 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (6183/6183), done.
Checking connectivity... done.
✔ ~/Downloads/iodbc
17:40 $ cd iODBC
✔ ~/Downloads/iodbc/iODBC [develop|✔]
17:40 $ cd mac/
✔ ~/Downloads/iodbc/iODBC/mac [develop|✔]
17:40 $ make
sh framework-include.sh
Building on Mac OS X 10.11
Projbuild is []
cd iODBCinst;		 build
/bin/sh: build: command not found
make: *** [all] Error 127
✘-2 ~/Downloads/iodbc/iODBC/mac [develop|✔]
17:40 $ git log -1
commit b8ede3cdd22223d2bc6cd80113950a9d755b4d24
Author: iODBC Maintainer <iodbc@openlinksw.com>
Date:   Thu Mar 10 15:44:41 2016 +0100

    Fixed issue with Xcode on Mac OS X 10.10 Xcode 7.2.1



The Xcode tools are installed. I have Xcode 7.2.1, and the tools are installed.

17:41 $ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
✘-1 ~/Downloads/iodbc/iODBC/mac [develop|✔]

**Comment by openlink** [comment]
Ah, there was a config option for 10.11 missing from the mac/Makefile. Please pull the latest fix which should resolve your build problem.

**Comment by pwagland** [comment]
This now works, so I can build it! This issue can be closed :-)

**Comment by 98B** [comment]
For macOS sierra (10.12), a similar addition to `mac/GNUMakefile` appears to make it work (tested using the psqlODBC driver; PostgreSQL lets me interact with it remotely, via the iODBC demo app).

When running _make_, I have deliberately ignored the effect of _FixupResourceForks_ seemingly gone in this edition of the OS.
> make: /System/Library/CoreServices/FixupResourceForks: No such file or directory

[GNUmakefile.diff.txt](https://github.com/openlink/iODBC/files/1034511/GNUmakefile.diff.txt)

**Comment by treadmillian** [comment]
Thank you for the patch.  Worked perfectly for macOS 10.12.6 with Xcode 9 beta 6 installed.
