### ISSUE TITLE
Anchor links not working in downloads page

### ISSUE THREAD

**Issue by walterdolce** [openlink/iODBC#20]
Hi,

I stumbled upon your website and I noticed none of your anchor links work on this page: http://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/Downloads

I thought I would let you know.
Best.

**Comment by openlink** [comment]
On 10 February 2017 at 12:23, Walter Dolce <notifications@github.com> wrote:

> I stumbled upon your website and I noticed none of your anchor links work
> on this page: http://www.iodbc.org/dataspace/doc/iodbc/wiki/
> iodbcWiki/Downloads
>

Hi,

Thanks for that. Have fixed (I think).

~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by walterdolce** [comment]
Yep, they work now :)
