### ISSUE TITLE
Accept environment variable reference when parsing ini?

### ISSUE THREAD

**Issue by tmaiaroto** [openlink/iODBC#25]
Hi,

This is more of a request for, or perhaps question about where I could look in the source to add, functionality. ODBC ini files are keeping credentials in plain text and I'm getting some people with security concerns over that.

I'd love to be able to simply reference environment variables in the ini files. So something like
```
[ODBC]
Host = blah.com
Password = ${ENV_PASSWD}
```
Is this something easy to add? Is it possible?

Would it be somewhere like here? https://github.com/openlink/iODBC/blob/bc100e72f535fe72a0508a96596dd9a46fe4984b/iodbcinst/inifile.c#L402

I'm more than happy to help implement it, I'd just need a few pointers (my C is rusty).

Thanks!

**Comment by HughWilliams** [comment]
Saving passwords in the "odbc.ini" file is not part for the ODBC spec (or iODBC itself), with the reading of passwords from INI is feature that some ODBC driver support, but really passwords should be passed by the application which has the responsibility of securing them.

We don't recommend storing the password in a world/public accessible "odbc.ini" file and would suggest if it is to be done then restrict access to the odbc.ini to a limited set of users.

**Comment by tmaiaroto** [comment]
Not storing a password there, bit referencing an environment variable.

The readme actually does suggest storing a password in the ini file.

Though at this point I have no idea what I was trying to use this for 😂
