### ISSUE TITLE
SQL_SUCCESS_WITH_INFO will not be returned from the driver to a caller of SQLExecDirect

### ISSUE THREAD

**Issue by chrisvittal** [openlink/iODBC#30]
At [this](https://github.com/openlink/iODBC/blob/2d9f3ddcf9bde377df23bf565353d61449975183/iodbc/execute.c#L584-L585) location, `retcode` is set to the return value of `_SQLExecute_ConvParams` which as far as I can tell, only returns `SQL_SUCCESS`, and as such will cause any `SQL_SUCCESS_WITH_INFO` retcode from a driver to not be returned to the caller of SQLExecDirect.

**Comment by smalinin** [comment]
Fixed in v 3.52.14
