### ISSUE TITLE
libiodbc on Fedora 29

### ISSUE THREAD

**Issue by Gjohn77** [openlink/iODBC#33]
iodbctest fails on Fedora 28 i686 with the following output when attempting to connect to SQL Server:

iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.1216.0712
1: SQLDriverConnect = ���������������������������������������� (20009) SQLSTATE=
2: SQLDriverConnect = ���������������������������������������� (20013) SQLSTATE=
3: SQLDriverConnect = ���������������������������������������� (0) SQLSTATE=
1: ODBC_Connect = ���������������������������������������� (20009) SQLSTATE=
2: ODBC_Connect = ���������������������������������������� (20013) SQLSTATE=
3: ODBC_Connect = ���������������������������������������� (0) SQLSTATE=

Have a nice day.[gjohnson@X4 ~]$ 

The tsql and isql command work fine so the odbc should be set up correctly.  This first failed in Fedora 22.  In the original release of Fedora 22, the iodbctest command worked correctly.  However, one of the patches to Freetds caused this to fail.

Version-Release number of selected component (if applicable):
libiodbc.i686                             3.52.12-5.fc28 

How reproducible:
iodbctest "DSN=database;UID=userid;PWD=password"

Steps to Reproduce:
1.iodbctest "DSN=database;UID=userid;PWD=password"

Actual results:  See above

Expected results:
iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.0709.0909
Driver: 0.91 (libtdsodbc.so)

SQL>

**Comment by smalinin** [comment]
Did you register your DSN in the odbc.ini file ?
Also you could run `$ iodbctest` without any parameters and enter `?` in the iodbctest, it will show you DSN list.
Also if you use the Unicode Enabled ODBC driver `libtdsodbc.so`, that was compiled with SIZEOF_SQLWCHAR = 2, so you must to use UnixODBC DM .
The current version of iODBC DM uses SIZEOF_SQLWCHAR = sizeof(wchar_t) = 4 in UnixSystems.

**Comment by Gjohn77** [comment]
The following is the result of running the iodbctest command without any parameters and then entering the ? character to see the DSN list and then selecting the Eligibility database:

[root@X4 etc]# iodbctest
iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.1216.0712

Enter ODBC connect string (? shows list): 

DSN                              | Driver                                  
------------------------------------------------------------------------------
Eligibility                      | FreeTDS                                 
Precision                        | FreeTDS                                 

Enter ODBC connect string (? shows list): Eligibility
1: SQLDriverConnect = ���������������������������������������� (20009) SQLSTATE=
2: SQLDriverConnect = ���������������������������������������� (20013) SQLSTATE=
3: SQLDriverConnect = ���������������������������������������� (0) SQLSTATE=
1: ODBC_Connect = ���������������������������������������� (20009) SQLSTATE=
2: ODBC_Connect = ���������������������������������������� (20013) SQLSTATE=
3: ODBC_Connect = ���������������������������������������� (0) SQLSTATE=

Have a nice day.[root@X4 etc]#


The following is the same test using the iodbctestw (Unicode):

[root@X4 etc]# iodbctestw
iODBC Unicode Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.1216.0712

Enter ODBC connect string (? shows list): ?

DSN                              | Driver                                  
------------------------------------------------------------------------------
Eligibility                      | FreeTDS                                 
Precision                        | FreeTDS                                 

Enter ODBC connect string (? shows list): Eligibility
1: SQLDriverConnectW = ���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������� (20009) SQLSTATE=����������1
2: SQLDriverConnectW = �������������������������������������������������������������������������������������������������������������������.���������������������������������������������������������������������������������������������������� (20013) SQLSTATE=����������0
3: SQLDriverConnectW = ����������������������������������������������������������������������������������������������������������������������������������e������������������������������������������������������������������������������������� (0) SQLSTATE=����������1
1: ODBC_Connect = 2: ODBC_Connect = 3: ODBC_Connect = 
[root@X4 etc]#

**Comment by smalinin** [comment]
1)
You must not enter `Eligibility`  here => `Enter ODBC connect string (? shows list): Eligibility`
It must be ODBC connection string i.e. something like:
`Enter ODBC connect string (? shows list): DSN=Eligibility;UID=myuid;PWD=mypwd;`
2) If your ODBC driver is the Unicode ODBC driver, the Unicode functions will call always.

**Comment by TallTed** [comment]
@Gjohn77 - It would be helpful if you would edit your posts, and wrap the terminal copy-and-paste sections with codefences, i.e., put a line with <code>```</code> above and below the pasted section.

**Comment by aabrah25** [comment]
I am having this problem on Redhat 8
I use libiodbc 3.52.13 and freetds 1.4.2

It works fine with tsql. But iodbctest produce error:
iodbctest "DSN=mssql;UID=xx;PWD=Jxx"
iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.1319.0723
1: SQLDriverConnect = ���������������������������������������� (20009) SQLSTATE=
2: SQLDriverConnect = ���������������������������������������� (20013) SQLSTATE=
3: SQLDriverConnect = ���������������������������������������� (0) SQLSTATE=
1: ODBC_Connect = ���������������������������������������� (20009) SQLSTATE=
2: ODBC_Connect = ���������������������������������������� (20013) SQLSTATE=
3: ODBC_Connect = ���������������������������������������� (0) SQLSTATE=

Any idea why? Thanks

**Comment by HughWilliams** [comment]
I note you are using an old [iODBC](https://www.iodbc.org) 3.52.13 release from 2019 and would recommend upgrading to the latest [iODBC](https://www.iodbc.org) 3.52.16 release from May 2023, as there were a number of unicode related fixes in the 3.52.14+ releases you will benefit from and probably resolve this problem ...

**Comment by aabrah25** [comment]
Hi @HughWilliams

Thanks for the quick response. I upgraded to iODBC 3.52.16 and still get the same results for iodbctest. See below
I've attached the ODBC trace file, and tsql dump file
When I run 'tsql -S mssql -U XX -P XX', I am able to connect

---------------------------------------------------------------------
[odbc-tracefile.log](https://github.com/openlink/iODBC/files/12848641/odbc-tracefile.log)
[freetds.log](https://github.com/openlink/iODBC/files/12848643/freetds.log)
----------------------
[aabrah25@mrpzbsphdb01 ~]$ iodbctest "DSN=mssqldsn;UID=XX;PWD=XX;DATABASE=XX"
iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.1623.0502
1: SQLDriverConnect = ��������������������������������������������� (20009) SQLSTATE=�
2: SQLDriverConnect = ��������������������������������������������� (20013) SQLSTATE=�
3: SQLDriverConnect = ��������������������������������������������� (0) SQLSTATE=�
1: ODBC_Connect = ��������������������������������������������� (20009) SQLSTATE=�
2: ODBC_Connect = ��������������������������������������������� (20013) SQLSTATE=�
3: ODBC_Connect = ��������������������������������������������� (0) SQLSTATE=�

Have a nice day.
---------------------------------------------------------------------------------------
The contents of my configuration files:


/etc/odbc.ini:
------------------------------------------------
[ODBC Data Sources]
mssqldsn = MSSQL DSNN

[ODBC]
TraceFile = /tmp/sql.trace
Trace = 1

[mssqldsn]
Driver = /usr/local/lib/libtdsodbc.so
Host = 40.75.119.172
Port = 1433

/etc/odbcinst.ini
-----------------------------------
[ODBC Drivers]
freetds = TDS Driver

[freetds]
Description = v0.91 with protocol v7.4
Driver = /usr/local/lib/libtdsodbc.so

---------------------
Any help would be much appreciated. Thanks!

**Comment by smalinin** [comment]
@aabrah25 
Try update your file **/etc/odbcinst.ini** like next:
```
[freetds]
Description = v0.91 with protocol v7.4
Driver = /usr/local/lib/libtdsodbc.so
DriverUnicodeType=UTF16
```
It looks your driver was compiled for use UTF16 Charset for Unicode Strings.
The iODBC DM uses UCS4 for Unicode String so you have the issue.
The new option **`DriverUnicodeType=UTF16`** will switch iODBC DM to use UTF16 for iteract via freetds odbc driver.
BUT you must to use the latest version of iODBC DM, that support this new option.

**Comment by aabrah25** [comment]
Thank you for the response. I put in 'DriverUnicodeType=UTF16' in odbcinst.ini and it iodbctest  gave the same output.
Then I put it in odbc.ini , right after "Driver =" line and the issue was resolved.  
So my /etc/odbc.ini looks like this now:

[ODBC Data Sources]
mssqldsn = MSSQL DSNN

[ODBC]
TraceFile = /tmp/sql.trace
Trace = 1

[mssqldsn]
Driver = /usr/local/lib/libtdsodbc.so
DriverUnicodeType=UTF16
Server = 40.75.119.172
Port = 1433
TDS_Version = 7.4

Appreciate all the  help. God bless
