### ISSUE TITLE
SQLSetStmtAttr caches the wrong value for some attributes

### ISSUE THREAD

**Issue by RGBradford** [openlink/iODBC#35]
The driver manager function SQLSetStmtAttr caches the wrong values in the statement when the client application sets any of these attributes:

- SQL_ATTR_ROW_ARRAY_SIZE
- SQL_ATTR_ROW_BIND_TYPE

Setting SQL_ATTR_ROW_ARRAY_SIZE results in rowset_size set to 27 regardless of the actual supplied value.
Setting SQL_ATTR_ROW_BIND_TYPE results in bind_type set to 5 regardless of the actual supplied value.

In both cases the attribute code is assigned to target variable instead of the attribute value.

The result is usually a crash in the client application.

**Comment by openlink** [comment]
merged
