### ISSUE TITLE
Trying to build on  OSX Mojave

### ISSUE THREAD

**Issue by peterhyvonen** [openlink/iODBC#39]
Hello super awesome people I'm getting 
$ make
sh framework-include.sh
Building on Mac OS X 10.12
Projbuild is []
cd iODBCinst;         build
/bin/sh: build: command not found
make: *** [all] Error 127

When trying to build on Mojave.
Seems very similar to https://github.com/openlink/iODBC/issues/1

Thanks in advance!

**Comment by peterhyvonen** [comment]
Apparently I had something hacky going on with my sdk but I'm still getting a similar error on a fresh box.
$ make
sh framework-include.sh
Building on Mac OS X 10.14
Projbuild is []
cd iODBCinst;		 build
/bin/sh: build: command not found
make: *** [all] Error 127

**Comment by smalinin** [comment]
Apply the next patch to ~\mac\GNUmakefile 
[patch.txt](https://github.com/openlink/iODBC/files/3497615/patch.txt)

the file ~\mac\GNUmakefile  doesn't have defines for OSX 10.12

**Comment by peterhyvonen** [comment]
that got me further. Thanks @smalinin !!!!!

**Comment by peterhyvonen** [comment]
Looks like I still have an issue on sudo make install step of the iODBC frameworks
#
#  Install CFM bridge for Microsoft Office
#
mkdir -p "/Library/CFMSupport/iODBC CFM Bridge"
install -m755 "iODBCcfmbridge/iODBC_CFM_Bridge" "/Library/CFMSupport/iODBC CFM Bridge"
install -m755 "iODBCcfmbridge/iODBC_CFM_Bridge.res" "/Library/CFMSupport/._iODBC CFM Bridge"
/System/Library/CoreServices/FixupResourceForks /Library/CFMSupport
make: /System/Library/CoreServices/FixupResourceForks: No such file or directory
make: *** [install] Error 1

Thanks in advance!

**Comment by smalinin** [comment]
The line
```
-/System/Library/CoreServices/FixupResourceForks /Library/CFMSupport
```
must ignore error with nonexistent `/System/Library/CoreServices/FixupResourceForks`
but you could drop this line also, the `iODBC CFM Bridge` is required for very old versions of MSOffice.

**Comment by peterhyvonen** [comment]
Sweet nuked it! Next questions is this step still relevant? 
2.  Setting up the MyODBC source tree.

    To setup the MyODBC tree execute the following commands:

	$ cd MyODBC-3.51.06


    Then we can either use the supplied myodbc.configure.diff file from
    the iODBC project using the command:

	$ patch -p1 < myodbc.configure.diff


It looks like theres no myodbc.configure.diff in the current version of the mac directory.

**Comment by smalinin** [comment]
Not actual for now.
You could download the precompiled binary of MySQL ODBC driver from MySQL site for OSX.
