### ISSUE TITLE
Broken conversion from UTF-32/UCS-4 to locale-dependent char*

### ISSUE THREAD

**Issue by pali** [openlink/iODBC#42]
iODBC also in its last version v3.52.13 has a problem with converting UTF-32/UCS-4 wchar_t* (SQLWCHAR*) buffer to ANSI char* which is in current locale (according to LC_CTYPE or LC_ALL variable). When current locale use multibyte encoding then every UTF-32/UCS-4 wchar_t* (SQLWCHAR*) buffer is truncated and not correctly/fully converted. iODBC do this without signaling any error or warning. It can be seen e.g. in en_US.UTF-8 locale.

Here is call trace of this problem:
https://github.com/openlink/iODBC/blob/f69576ee643ebe243da23b637ca6f9bd5b96d0b2/iodbc/hstmt.c#L1275
https://github.com/openlink/iODBC/blob/f69576ee643ebe243da23b637ca6f9bd5b96d0b2/iodbc/hstmt.c#L1295-L1298
https://github.com/openlink/iODBC/blob/f69576ee643ebe243da23b637ca6f9bd5b96d0b2/iodbc/hstmt.c#L1300
https://github.com/openlink/iODBC/blob/f69576ee643ebe243da23b637ca6f9bd5b96d0b2/iodbc/hstmt.c#L1311-L1318
https://github.com/openlink/iODBC/blob/f69576ee643ebe243da23b637ca6f9bd5b96d0b2/iodbcinst/unicode.h#L129

Main problem is at line 1300. It should be `size * MB_LEN_MAX + 1`. And call to `OPL_W2A` should have not `size`, but rather `size * MB_LEN_MAX`.

C99 macro `MB_LEN_MAX` expands to maximal number how many bytes are needed to store one character in char* string.

Also problem is that return value from `wcstombs` is ignored. When function `wcstombs` fails then buffer may be uninitialized and may contain values from previous calls. So this could have also security impact that attacker could cause reusing of some buffer and cause passing it to some ODBC SQL function...

**Comment by TallTed** [comment]
@smalinin - Please look into this.

**Comment by smalinin** [comment]
It will be fixed in the next iODBC release v3.52.14, that will coming soon.

**Comment by pali** [comment]
Ok, when you merge code into this repository, let us know!

**Comment by smalinin** [comment]
@pali New updated code is in the *develop* branch.

**Comment by pali** [comment]
Hello @smalinin I looked at implementation in develop branch. Problems described in first post about `MB_LEN_MAX` are fixed.

But there is another a new issue which breaks processing strings from current locale encoding to UTF-8. Problem is on these lines:

https://github.com/openlink/iODBC/blob/4a74e3a3a4715d0a102588c09d866c81363e9745/iodbcinst/unicode.c#L1919-L1927

You are clearing shift state `st` prior to processing a new byte which breaks whole conversion. You must declare `mbstate_t st` state prior to entering while loop and also initialize (clear) only prior to while loop. This is how `mbrtowc` API needs to be used. `mbrtowc` is a state function and it stores its state into `st` variable which needs to be preserved until whole string is processed.

**Comment by pali** [comment]
Another problem: There is a wrong check for maximal Unicode code point. On more places is check for `Char < 0x200000`, but maximal value is only `0x10FFFF`:
https://github.com/openlink/iODBC/blob/4a74e3a3a4715d0a102588c09d866c81363e9745/iodbcinst/unicode.c#L646
https://github.com/openlink/iODBC/blob/4a74e3a3a4715d0a102588c09d866c81363e9745/iodbcinst/unicode.c#L671

**Comment by pali** [comment]
When doing conversion to UTF-8 and input sequence is somehow invalid, new code using ASCII questionmark `?` as a replacement character for invalid input sequence. But in Unicode there is a speciall code point reserved for this purpose `U+FFFD`. Encoded in UTF-8 it is `0xEF 0xBF 0xBD` and it should be used instead of ascii `0x3F` (`?`).

**Comment by pali** [comment]
> Problems described in first post about `MB_LEN_MAX` are fixed.

Seems, this is not truth. Here are still some places where multibyte length multiplicator is not used:

https://github.com/openlink/iODBC/blob/4a74e3a3a4715d0a102588c09d866c81363e9745/iodbcinst/unicode.c#L2086-L2090
https://github.com/openlink/iODBC/blob/4a74e3a3a4715d0a102588c09d866c81363e9745/iodbcinst/unicode.c#L2611-L2638
https://github.com/openlink/iODBC/blob/4a74e3a3a4715d0a102588c09d866c81363e9745/iodbcinst/unicode.c#L2666-L2691

**Comment by pali** [comment]
Hello @smalinin, @TallTed, would you fix remaining problems with ansi buffers?

**Comment by smalinin** [comment]
@pali Yes, I am working with issues above now.

**Comment by pali** [comment]
Thanks for update!

**Comment by smalinin** [comment]
@pali Commited to develop branch

**Comment by smalinin** [comment]
@pali 
> 
> 
> 
> https://github.com/openlink/iODBC/blob/8ef7ef007bba15595aafe240a686bd06175a0f57/iodbcinst/unicode.c#L1514-L1526
> 
> `mbrtowc` returns `(size_t)-1` or `(size_t)-2` on error. And in this case `wc` is undefined and it is incorrect to pass it to `eh_encode_char__UTF16LE`. I think that `0xFFFD` (replacement char) could be assigned to `wc` and `src` ptr increased by one (to process next byte).
> 
> https://github.com/openlink/iODBC/blob/8ef7ef007bba15595aafe240a686bd06175a0f57/iodbcinst/unicode.c#L1553-L1561
> 
> https://github.com/openlink/iODBC/blob/8ef7ef007bba15595aafe240a686bd06175a0f57/iodbcinst/unicode.c#L1586-L1594
> 
> Same there `wc` is not filled on `mbrtowc` error.
> 

Fixed.

> There is another thing. In code which uses `wcrtomb` function you correctly moved `mbstate_t st` variable above `while` loop to preserve state of conversion, but you forgot to flush buffer and reset shift state in output buffer after the last `wcrtomb` call. E.g. by `wcrtomb(temp, L'\0', &st);` call and then modifying `temp` buffer (as that call puts there nul byte). It is a bit complicated, but this is how `wcrtomb` API should be used.

The above was fixed already, I commited additional fixes already for some another things, that include the error above.
Shift state is reset via:
```
      memset (&st, 0, sizeof (st));
```
The updates will be in Git soon.
