### ISSUE TITLE
Expired Certificate in the pre-compiled osx downloads

### ISSUE THREAD

**Issue by ebrose** [openlink/iODBC#43]
Hey just wanted to let those know.
the certificate expired last night for the bits located here
http://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/Downloads#Mac%20OS%20X
mojave will not install them without adding an additional warning.
Is there a plan to re-compile the bits on this end? 
Regards,
Eric

**Comment by TallTed** [comment]
Fresh pre-built downloads should be forthcoming shortly.

/cc @smalinin @pkleef @openlink

**Comment by ebrose** [comment]
Thank you so much @TallTed, will you notify and close this issue out when the download has been updated? 
Regards,
Eric

**Comment by smalinin** [comment]
@ebrose 
The OSX iODBC installer was updated, it could be download from the same URL 
http://download3.openlinksw.com/uda/components/7.0/universal-apple-macosx10.7-32/mxkozzzz.dmg

**Comment by ebrose** [comment]
Thanks @smalinin
