### ISSUE TITLE
iODBC website not using https

### ISSUE THREAD

**Issue by ghost** [openlink/iODBC#44]
Is there an alternative site that one visit that contains the downloadable software packages and uses https
?
I know one can install from source but many of us are not familiar with the technology used or have the time to learn.

Thanks.

**Comment by TallTed** [comment]
For what platform do you want the pre-compiled software?

Can you provide the `http` link(s) for the archive(s) you want via `https`?  I can quickly provide a corresponding `https` link for each.

**Comment by ericmatias** [comment]
Sorry for the late reply. This would be the site:

http://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/Downloads

**Comment by pkleef** [comment]
We just released [iODBC SDK version 3.52.15](https://github.com/openlink/iODBC/releases/tag/v3.52.15) with notarized binaries.
