### ISSUE TITLE
Typo in iodbcext.h: SQL_DD_CP_UTF16

### ISSUE THREAD

**Issue by pali** [openlink/iODBC#46]
In iodbcext.h is typo in macro names:
https://github.com/openlink/iODBC/blob/4a74e3a3a4715d0a102588c09d866c81363e9745/include/iodbcext.h#L218-L220

These macro names are named `SQL_DD_CP_UTF16` and `SQL_DD_CP_UTF8`. Not `_*DM_*`. At least all other ODBC implementations uses `*_DD_*` in names, not `*_DM_*`. Even google was not able to find any result for `SQL_DD_CP_UTF16`.

Therefore I think this is a typo.

**Comment by smalinin** [comment]
It isn't a type, it is iODBC macro defines, but I agree, that `SQL_DD_CP_UTF16` and `SQL_DD_CP_UTF8` macros from DataDirect ODBC DriverManager must be added to `iodbcext.h` for compatibility.

**Comment by pali** [comment]
Is there are a reason why not to reuse DataDirect defines (`*_DD_*`) instead of inventing names for iODBC (`*_DM_*`)? Existing applications already use `*_DD_*` macros, so for me it looks like that the best is to reuse existing macros which should prevent #ifdef-s in ODBC applications.

**Comment by smalinin** [comment]
The next defines will be added:
```
#define SQL_DD_CP_ANSI				0 
#define SQL_DD_CP_UCS2				SQL_DM_CP_UTF16
#define SQL_DD_CP_UTF8				SQL_DM_CP_UTF8
#define SQL_DD_CP_UTF16			SQL_DD_CP_UCS2
```
if Copyright allows it.
Note also that `SQL_DD_CP_ANSI` isn't supported by iODBC DM.

**Comment by pali** [comment]
> Note also that SQL_DD_CP_ANSI isn't supported by iODBC DM.

I know, that is fine.

**Comment by pali** [comment]
But I'm asking, why should I use `SQL_DM_CP_UTF8` define, if there is `SQL_DD_CP_UTF8` which will be supported by both DataDirect and iODBC, but `SQL_DM_CP_UTF8` only by iODBC.

For application developer does not make sense to use `SQL_DM_CP_UTF8` at all as it is iODBC specific.

**Comment by smalinin** [comment]
The iODBC DM support was created for compatibility with DD ODBC DM, but we use another options list. For example we support: `#define SQL_DM_CP_UCS4			3` , that is not existed in DD ODBC DM.

And you will be able to use `SQL_DD_CP_UTF8` also, when the fix above is committed to git.

**Comment by pali** [comment]
> The iODBC DM support was created for compatibility with DD ODBC DM, but we use another options list. For example we support: `#define SQL_DM_CP_UCS4 3` , that is not existed in DD ODBC DM.

Yes, I saw it, that UCS4 is iODBC specific, but UTF8 and UTF16 are supported by both implementation (DataDirect and iODBC).

> And you will be able to use `SQL_DD_CP_UTF8` also, when the fix above is committed to git.

Ok. I understood this part.

But I'm thinking if it was not better to just reuse namings from DataDirect and do not use a new SQL_DM_CP_UTF8 and SQL_DM_CP_UTF16 names. Just only SQL_DD_CP_UCS2 and SQL_DD_CP_UTF8. And then define a new SQL_DD_CP_UCS4 to 3 (which is not supported by DataDirect).

**Comment by smalinin** [comment]
We will not reuse DataDirect proprietary defines in our code directly.

**Comment by pali** [comment]
Ok, I understand.

Thank you for input and adding these aliases! (I hope that they appear in git)
