### ISSUE TITLE
Mixing calls to SQLFetchScroll with SQLFetch returns Function Sequence Errors

### ISSUE THREAD

**Issue by tmacphail** [openlink/iODBC#48]
Attempting to call SQLFetchScroll after SQLFetch while retrieving the same result returns a function sequence error.

At an initial glance, it appears to be due to both SQLFetchScroll and SQLExtendedFetch internally sharing the statement state "en_stmt_cursor_xfetched". And the check at the start of SQLFetchScroll doesn't allow en_stmt_cursor_fetched. Perhaps SQLFetchScroll should share the en_stmt_cursor_fetched state with SQLFetch.

The relevant quote from the ODBC spec is:
> Calls to SQLFetchScroll can be mixed with calls to SQLFetch but cannot be mixed with calls to SQLExtendedFetch.

**Comment by smalinin** [comment]
@tmacphail 
Fixed.
