### ISSUE TITLE
Mac Installation Package

### ISSUE THREAD

**Issue by alexanderisascson** [openlink/iODBC#49]
I have tried to get iODBC working with Excel. 

Did get version 3.52.12 to connect and fetch data to Excel but the charset was off. 
(This was no simple task but thanks to https://stefan-schaffner.de/posts/using-odbc-driver-on-macos-and-excel-to-access-a-mysql-database/ I finally got it working early last year)
However Swedish characters like å ä ö didn't show up correctly. No matter which setting is used in odbc.ini. So I relied on running excel inside Virtual Box.

Now I saw that you released version 3.52.13 in June so I tried to install that. But it didn't have a Mac .pkg file. So I used homebrew.sh to install it. It works with iodbctest !I do get the correct characters with the new version! Joy! However I can't get excel to find it.

Could you please package 3.52.13 in a Mac .pkg file so that I can install the new version?

I sit correct to assume that the homebrew version doesn't contain the needed framework for excel to find iODBC?

I tried to simply copy the new libs and files form the homebrew install over the libraries and other files from the 3.52.12 but I got permission denied trying to replace libiodbc in /usr/lib.

Please help

**Comment by smalinin** [comment]
The latest installer binary ver 3.52.14 could be downloaded from 
http://download3.openlinksw.com/uda/components/8.0/universal-apple-macosx10.7-32/mxkozzzz.dmg
