### ISSUE TITLE
Certificate Expired for iODBC Driver

### ISSUE THREAD

**Issue by jacobkn** [openlink/iODBC#52]
Hey,

I just wanted to let you know that the following certificate for this package appears to have expired October 22nd 2019. http://opldownload.s3.amazonaws.com/uda/components/7.0/universal-apple-macosx10.7-32/mxkozzzz.dmg You can also reach it via this link http://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/Downloads#Mac%20OS%20X

Are there plans to republish this with an updated certificate?

**Comment by smalinin** [comment]
The latest installer binary ver 3.52.14 could be downloaded from
http://download3.openlinksw.com/uda/components/8.0/universal-apple-macosx10.7-32/mxkozzzz.dmg

**Comment by TallTed** [comment]
@jacobkn - Please confirm whether the newer installer resolved the issue for you, and (assuming so) whether we may therefore mark this issue CLOSED.

**Comment by jacobkn** [comment]
The newer installer worked. Thanks for your assistance!
