### ISSUE TITLE
Apple Notarization Required for Installation on Catalina

### ISSUE THREAD

**Issue by jdanielmyers** [openlink/iODBC#53]
Hi,

This software is blocked by Apple Gatekeeper on Catalina (or later) and requires apple notarization in order for end-user installation to work. 

![image](https://user-images.githubusercontent.com/2223194/91332060-3a250400-e791-11ea-9ac0-3bfbc077457e.png)

Apple has instructions here on how to fix this problem: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

Can the openlink team please work with Apple to notarize the release?

**Comment by jovanzulich** [comment]
thanks for opening this issue - I am also blocked! 

While using: MacOS 10.5.5
I cannot complete the [MySQL-Tableau setup process](https://www.tableau.com/en-us/support/drivers?edition=pro&lang=en-us&platform=mac&cpu=64&version=2020.3&__full-version=20203.20.0801.1333#mysql) due to system rejecting use of file: mxkozzzz.dmg

**Comment by smalinin** [comment]
Try the next:
- download latest installer http://download3.openlinksw.com/uda/components/8.0/universal-apple-macosx10.7-32/mxkozzzz.dmg
- open package and run installer, you will get dialog
![Screenshot 2019-10-04 at 03 33 15](https://user-images.githubusercontent.com/765462/91940136-53eabc00-ed3a-11ea-841b-cbaf76c4272d.png)
- click on [Ok] and close this popup dialog
- open OSX System Preferences -> Security & Privacy , you will see the next
![Screenshot 2019-10-04 at 03 34 21](https://user-images.githubusercontent.com/765462/91940303-944a3a00-ed3a-11ea-8726-15e4dbcf2ca9.png)
  click [Open Anyway] here
- the installer will be restarted and you will see the next popup now
![Screenshot 2019-10-04 at 03 34 59](https://user-images.githubusercontent.com/765462/91940431-c196e800-ed3a-11ea-8dd3-9018f004d27b.png)
 now you could click on [Open] button and installer will continue, but it will show the next popup, related with sign certificate
![Screenshot 2019-10-04 at 03 36 51](https://user-images.githubusercontent.com/765462/91940555-fc991b80-ed3a-11ea-8ac8-d211f51b71d4.png)
  click on [Continue] button for continue installation process

**Comment by jdanielmyers** [comment]
@smalinin your workaround does not work for people who do not have admin privileges on their system or corporate policies that do not allow them to make this change. 

Will the openlink team please work with Apple to properly notarize this application?

**Comment by openlink** [comment]
OpenLink is currently working on getting iODBC noterized

**Comment by TallTed** [comment]
@openlink @smalinin -- Just a nudge for current status on this...

**Comment by naubryGV** [comment]
Correct me if I'm wrong, but as long as you have an Apple Dev account, notarizing should be just a matter of a simple command no? why would it takes 3+ months?

**Comment by TallTed** [comment]
@openlink @pkleef @smalinin @hughwilliams

What's the status on this?  Were the recently shipped 3.52.14 installers notarized?

**Comment by babegeman** [comment]
> @openlink @pkleef @smalinin @HughWilliams
> 
> What's the status on this? Were the recently shipped 3.52.14 installers notarized?

No. As far as I can tell there is no installer that is notarized.

**Comment by HughWilliams** [comment]
We are currently working on a new set of notarised components of all our product offerings on macOS, which should be available in the coming weeks. In the meantime this notarisation issue can be worked around as detailed at:

     https://community.openlinksw.com/t/apple-software-notarisation-issues-on-macos/2155

**Comment by babegeman** [comment]
> We are currently working on a new set of notarised components of all our product offerings on macOS, which should be available in the coming weeks. In the meantime this notarisation issue can be worked around as detailed at:
> 
> https://community.openlinksw.com/t/apple-software-notarisation-issues-on-macos/2155

I just attempted this and the same window that opening the installer with a double-click would show appears. No option to continue opening the installer.

**Comment by TallTed** [comment]
@babegeman - What version of macOS (preferably to the second decimal, e.g., `10.11.2`), and on what hardware (`x86_64`, or `arm64` a/k/a `M1`), are you running?

**Comment by babegeman** [comment]
> @babegeman - What version of macOS (preferably to the second decimal, e.g., `10.11.2`), and on what hardware (`x86_64`, or `arm64` a/k/a `M1`), are you running?

`11.2.3`, it's a MacBook Pro 16" 2019, so it's `x86_64`

**Comment by pkleef** [comment]
We just released [iODBC version 3.52.15](https://github.com/openlink/iODBC/releases/tag/v3.52.15) that contains notarized installers.
