### ISSUE TITLE
libiodbcinst.dylib is missing macOS Big Sur

### ISSUE THREAD

**Issue by ausiddiqui** [openlink/iODBC#57]
When trying to onfigure a driver (Teradata ODBC Driver) using iODBC Administrator I get the warning dialog box with an OK button:

Dynamic Library Error
libiodbcinst.dylib is missing. 

This is on macOS Big Sur 11.2.3 and I installed OpenLink iODBC Driver Manager v3.52.14 through the dmg file in the release link on GitHub.

There are only two copies of libiodbcinst.dylib on my machine:
`/usr/local/iODBC/lib` -- symbolic link to `//Library/Frameworks/iODBCinst.framework/iODBCinst`
`/usr/lib` -- this is a broken symbolic link to `libiodbcinst.2.1.18.dylib`

This second link in `/usr/lib` cannot be edited, removed and a new link cannot be added in this directory (even with sudo).

I have added `/usr/local/iODBC/lib` to both my `PATH` and `DYLD_LIBRARY_PATH` environment variables without any luck.

**Comment by TallTed** [comment]
Interesting.

Have (or will) you set up `locate` on your machine?  If so, please provide the output of --
```pre
locate -0 libiodbcinst | xargs -0 sudo ls -l
```

If you haven't (and don't want to) set up `locate`, please provide output of this command (which will take somewhat longer to run, especially if you have mounted any network volumes) --
```pre
sudo find / -name "*libiodbcinst*" -print0 | xargs -0 sudo ls -l
```

**Comment by pkleef** [comment]
I have downloaded the Teradata driver on my Big Sur system and recreated your error.

It indeed looks like Apple is only installing the symlinks to their build of the `libiodbcinst.2.1.18.dylib`, but _forgot_ to actually install the library itself in `/usr/lib`. As this directory cannot be changed by a user (or root for that matter) we cannot directly fix the issue in our installers. We can try to raise a problem report to Apple, but it is unsure how long this may take.

Your idea to change the DYLD_LIBRARY_PATH unfortunately also does not work transparently, unless you set it on some system-wide level. Starting the iODBC Administrator64.app from the UI does not inherit the environment settings from your shell.

As it looks like Teradata is not directly linking to the libiodbcinst.dylib library, but loads the library dynamically when the dialog is instantiated, you should report this problem to them and tell them to contact us. We would be more than happy to work with them to fix this issue for their customers. 

So i checked if i could fix the Teradata installation on my system. 

First i went to the directory where the setup dialog has been written by looking at my `/Library/ODBC/odbcinst.ini` which has the following lines:
```
[Teradata Database ODBC Driver 16.20]
Driver = /Library/Application Support/teradata/client/16.20/lib/tdataodbc_sbu.dylib
Setup  = /Library/Application Support/teradata/client/16.20/lib/TeradataODBCSetup.bundle/Contents/MacOS/TeradataODBCSetup
```

So on my system i ran the following commands:
```
cd "/Library/Application Support/teradata/client/16.20/lib/TeradataODBCSetup.bundle/Contents/MacOS/"

otool -l TeradataODBCSetup
```
to see which library path references there are. As mentioned before the `libiodbcinst.dylib` was not  in that list, which means the setup dialog code must load it at runtime. Cross checking the same driver on Mojave it is clear that it does pick up the `/usr/lib/libiodbcinst.2.1.18.dylib` via the symlink correctly.

The workaround i came up with, is to add an extra runtime search path to the setup dialog code.

I have tested the following method, but i have to warn you it will break the code signatures from Teradata at some point in time Apple may stop running code with broken spctl/codesign signatures.  However so far i have been able to use the setup dialogs without a problem.

I used the following command:
```shell

cd "/Library/Application Support/teradata/client/16.20/lib/TeradataODBCSetup.bundle/Contents/MacOS/"

sudo install_name_tool --add_rpath /usr/local/iODBC/lib TeradataODBCSetup

```

*NOTE*: you will get the following warnings but for now this solution will work.
```
Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: TeradataODBCSetup (for architecture x86_64)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: TeradataODBCSetup (for architecture i386)
```

You should now be able to configure a DSN using the `iODBC Administrator64.app`

**Comment by TallTed** [comment]
@ausiddiqui -- Can you confirm whether [the above](https://github.com/openlink/iODBC/issues/57#issuecomment-819541153) brought you success? 

Please also note that new installers of iODBC 3.52.15 have just been posted, which will bring improved experience on macOS Big Sur.

**Comment by ausiddiqui** [comment]
The symbolic linking @pkleef suggested worked. Thank you!
