### ISSUE TITLE
autogen.sh uses incorrect test to determine if a tool is installed

### ISSUE THREAD

**Issue by vt-pongrass** [openlink/iODBC#64]
On my computer, I don't have the GNU autotools installed so when autogen.sh is executed, I expected it to report the tools were missing. It does not do this. I believe it's because line 109 and line 131 are both using the wrong test:

if test -z "VERSION"

instead of

if test -z "$VERSION"

When I changed my copy, the missing tools were then correctly reported as missing.

**Comment by TallTed** [comment]
Development will be looking into this shortly.  To help us prevent this issue going forward, would you please also provide your OS name and version?

/cc @smalinin @pkleef @openlink

**Comment by pkleef** [comment]
I have pushed a fix for this issue to the `develop` branch.

**Comment by TallTed** [comment]
For ease of future reference, that fix is in https://github.com/openlink/iODBC/commit/aa40083c398adc32e7ff875b81b27958e7a448e0.
