### ISSUE TITLE
Installation documentation?

### ISSUE THREAD

**Issue by JoeMurray** [openlink/iODBC#7]
I want to migrate a postgreSQL db to MySQL, and I'm working on OS X 10.9. I work on open source LAMP projects.

MySQL Workbench wants an ODBC driver manager to be installed so that a psqlodb driver from http://www.postgresql.org/ftp/odbc/versions/src/ can be installed. I don't really ever use Xcode, but I've got it installed, and its command line tools as well. It seems I need an iodbc version for Mavericks, which http://sourceforge.net/projects/iodbc/files/iodbc/3.52.9/ provides. 

(I don't really want to pay ActualTech for their solution, and I can't tell if http://www.odbcmanager.net/index.php supports 10.9.)

How does one install iodbc on a Mac, particularly 10.9? Link to a document would be great.

**Comment by openlink** [comment]
Build instructions are in the [ReadME file for Mac OS X](https://github.com/openlink/iODBC/blob/develop/README.MACOSX) as part of the source code.
