### ISSUE TITLE
Memory leak if too many diagnostics are returned

### ISSUE THREAD

**Issue by matthew-wozniczka** [openlink/iODBC#71]
I haven't confirmed this, but I was looking through the code, and it looks like https://github.com/openlink/iODBC/blob/79c7f572a7b5c4123ec3cc1dd29df1af61a3405f/iodbc/herr.c#L154 will leak memory, as it overwrites perr->msg without freeing the previous value.

**Comment by TallTed** [comment]
Interesting.  We'll have a look.
