### ISSUE TITLE
Comparison with unixODBC?

### ISSUE THREAD

**Issue by ghost** [openlink/iODBC#89]
https://github.com/lurcher/unixODBC

**Comment by TallTed** [comment]
I [posted the following to StackOverflow](https://stackoverflow.com/a/66247796/241164) a few years ago. So far as I know, it's all still accurate (modulo "latest version" details).

-----

[iODBC][3] and [unixOBDC][4] are basically API equivalent, both being cross-platform implementations of Microsoft's [ODBC standard][5]. iODBC's flexible Unicode support includes UCS-2, UTF-8, UCS-4. iODBC libraries are bundled into macOS Panther ([10.3.0][6]) through Big Sur ([11.2.x][7]), and may be built and/or installed on AIX, Solaris, HP-UX, any Linux distribution, *BSD, other Unix-like OS, and more. iODBC has been thread safe for a very long time, and is actively maintained and supported by [OpenLink Software][8] (my employer).

The table below covers the most common comparative questions *(is there something I should add?)*, and is based on iODBC 3.52.14, as of February 2021 (reports version `03.52.1421.0217`), and unixODBC 2.3.9, as of September 2020.

For a somewhat more detailed comparison, and a much more fancy and detailed table, see [this spreadsheet](https://docs.google.com/spreadsheets/d/1jbcOfNgA5jXpYLo54kiIWRHcJp9kpH6j00pikpO93z0/edit?usp=sharing)

| **feature**                                                        | **[iODBC](http://iodbc.org/)**            | **[UnixODBC](http://unixodbc.org/)** |
|:------------------------------------------------------------------ |:-----------------------------------------:|:------------------------------------:|
| ***Unicode support***                                              |                                           |                                      |
| &nbsp; &nbsp; *[UCS-2](http://dbpedia.org/resource/UCS-2)*                       | YES                                       | YES                                  |
| &nbsp; &nbsp; *[UCS-4 (a/k/a UTF-32)](http://dbpedia.org/resource/UCS-4)*        | YES                                       | NO                                   |
| &nbsp; &nbsp; *[UTF-08 (a/k/a UTF-8)](http://dbpedia.org/project/UTF-8)*         | YES                                       | NO                                   |
| &nbsp; &nbsp; *[UTF-16](http://dbpedia.org/project/UTF-16)*                      | YES                                       | YES                                  |
| &nbsp; &nbsp; *[UTF-32 (a/k/a UCS-4)](http://dbpedia.org/project/UTF-32)*        | YES                                       | NO                                   |
| ***Supports drivers and apps <br /> developed using other SDKs***  |                                           |                                      |
| &nbsp; &nbsp; *Supports drivers developed using iODBC SDK*                       | YES                                       | NO                                   |
| &nbsp; &nbsp; *Supports apps developed using iODBC SDK*                          | YES                                       | NO                                   |
| &nbsp; &nbsp; *Supports drivers developed using unixODBC SDK*                    | YES                                       | YES                                  |
| &nbsp; &nbsp; *Supports apps developed using unixODBC SDK*                       | YES                                       | YES                                  |
| &nbsp; &nbsp; *Supports drivers developed using DataDirect SDK*                  | YES                                       | NO                                   |
| &nbsp; &nbsp; *Supports apps developed using DataDirect SDK*                     | YES                                       | NO                                   |
| ***OS default DM***                                                |                                           |                                      |
| &nbsp; &nbsp; *macOS*                                                            | YES                                       | NO                                   |
| &nbsp; &nbsp; *Linux*                                                            | partial                                   | partial                              |
| &nbsp; &nbsp; *Unix-like*                                                        | partial                                   | partial                              |
| ***OS support***                                                   |                                           |                                      |
| &nbsp; &nbsp; *macOS*                                                            | YES                                       | partial                              |
| &nbsp; &nbsp; *Linux*                                                            | YES                                       | YES                                  |
| &nbsp; &nbsp; *Unix-like*                                                        | YES                                       | YES                                  |
| ***User-friendly native GUI Administrator***                       |                                           |                                      |
| &nbsp; &nbsp; *macOS*                                                            | YES                                       | Qt-based                             |
| &nbsp; &nbsp; *Linux*                                                            | GTK-based and HTML-based                  | Qt-based                             |
| &nbsp; &nbsp; *Unix-like*                                                        | GTK-based and HTML-based                  | Qt-based                             |
| ***Thread Safe***                                                  | YES                                       | YES                                  |
| ***Support***                                                      |                                           |                                      |
| &nbsp; &nbsp; *Mailing List(s)*                                                  | YES                                       | YES                                  |
| &nbsp; &nbsp; *Forum(s)*                                                         | YES                                       | YES                                  |
| &nbsp; &nbsp; *Github repository*                                                | YES                                       | YES                                  |
| &nbsp; &nbsp; *SourceForge repository*                                           | YES                                       | YES                                  |
| ***Open Source Licensing***                                        |                                           |                                      |
| &nbsp; &nbsp; *GPL*                                                              | NO                                        | [programs](https://github.com/lurcher/unixODBC/blob/master/README) |
| &nbsp; &nbsp; *LGPL*                                                             | [YES](http://github.com/openlink/iODBC/blob/develop/LICENSE.LGPL)                                       | [libraries](https://github.com/lurcher/unixODBC/blob/master/LICENSE) |
| &nbsp; &nbsp; *BSD*                                                              | [YES](http://github.com/openlink/iODBC/blob/develop/LICENSE.BSD) | NO                                   |


## Notes

### Unicode a/k/a Wide Characters

* iODBC supports and translates between all of UCS-2, UCS-4, UTF-8, UTF-16, UTF-32
* unixODBC follows MDAC, and `SQLWCHAR`s are 2 bytes UCS2 encoded

### SDK lock-in

* iODBC supports applications and drivers developed using unixODBC SDK and DataDirect SDK as well as those developed using iODBC SDK
* unixODBC only supports applications and drivers developed using unixODBC SDK


  [1]: https://stackoverflow.com/questions/7548825/what-are-the-functional-differences-between-iodbc-and-unixodbc/66247796#comment53536413_7552533
  [2]: https://stackoverflow.com/a/7552533/241164
  [3]: http://iodbc.org/
  [4]: http://www.unixodbc.org/
  [5]: https://learn.microsoft.com/en-us/sql/odbc/reference/odbc-programmer-s-reference?view=sql-server-ver15
  [6]: https://opensource.apple.com/release/mac-os-x-103.html
  [7]: https://opensource.apple.com/release/macos-112.html
  [8]: https://www.openlinksw.com/
