### ISSUE TITLE
SQLGetData doesn't support SQL_ARD_TYPE

### ISSUE THREAD

**Issue by matthew-wozniczka** [openlink/iODBC#91]
See https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/sql-ard-type?view=sql-server-ver16

When trying to use it, the error `[iODBC][Driver Manager]Program type out of range` is returned. I found this issue in 3.52.8, but looking at the current source code it hasn't been changed.

**Comment by HughWilliams** [comment]
Development are looking into this ...

**Comment by aleksei-i** [comment]
We are running integration tests with iODBC driver manager we got the following error: "[iODBC][Driver Manager]Program type out of range". When I had a look at the implementation the SQL_ARD_TYPE is not under a case in SQLGetData() so the default error is reported.

**Comment by pkleef** [comment]
@aleksei-i @matthew-wozniczka 
This issue was fixed with commit  https://github.com/openlink/iODBC/commit/3c728d66ab625c25b02a9ce4c92e2061c8ecee1c on the develop branch
