### ISSUE TITLE
iODBC on redhat entreprise 8

### ISSUE THREAD

**Issue by fred-the-coder** [openlink/iODBC#94]
Dear all,

Where can I find an RPM package of iODBC manager for redhat enterprise 8.

I have found one here https://sourceforge.net/projects/iodbc/files/iodbc/3.51.1/
but it looks not 64bits but 32 bits.

Actually, I need iODBC manager on RedHat...how to?

Thanks for your help.

**Comment by pkleef** [comment]
Development is looking into this.

**Comment by pkleef** [comment]
I have uploaded a set of RPMS for RedHat Enterprise linux 8 (also usable on Centos 8, AlmaLinux 8, Rocky Linux 8 and Oracle Linux 8) containing a 64bit port of the current version of iODBC v3.52.16:

https://sourceforge.net/projects/iodbc/files/iodbc/3.52.16/RHEL8/
    
Please let me know if this solves your requirement.

**Comment by pkleef** [comment]
Note that the RedHat/Fedora EPEL 8 repository contains an older version of iODBC: 3.52.13 which does not contain the latest fixes:

```
$ sudo dnf info libiodbc
Last metadata expiration check: 0:14:49 ago on Thu Oct 26 12:54:56 2023.
Available Packages
Name         : libiodbc
Version      : 3.52.13
Release      : 1.el8
Architecture : x86_64
Size         : 195 k
Source       : libiodbc-3.52.13-1.el8.src.rpm
Repository   : epel
Summary      : iODBC Driver Manager
URL          : http://www.iodbc.org/
License      : LGPLv2 or BSD
Description  : The iODBC Driver Manager is a free implementation of the SAG CLI and
             : ODBC compliant driver manager which allows developers to write ODBC
             : compliant applications that can connect to various databases using
             : appropriate backend drivers.
```

This version is from Tue Jul 23 11:37:41 2019 so is lacking a number of important fixes we made recently, however depending on your application, or the driver you are using, this version may suffice.

**Comment by fred-the-coder** [comment]
Thank you very much @pkleef !

> This version is from Tue Jul 23 11:37:41 2019 so is lacking a number of important fixes we made recently, however depending on your application, or the driver you are using, this version may suffice.

Do those fixes not part of this Github repository?

I'll close this issue (which is not one actually!) follwing your answer.

**Comment by pkleef** [comment]
Let me answer your question:

> Are those fixes not part of this Github repository?

Note that https://github.com/openlink/iODBC is the canonical project tree for iODBC and therefor contains the most up-to-date source version of iODBC. At this time the latest release is v3.52.16 which was released on Tue May 2 13:17:03 2023. 

However the EPEL repository only has version v3.52.13 which was released on Tue Jul 23 11:37:41 2019 as their maintainers have not downloaded the latest release from us. I will attempt to contact their maintainers to see if they are willing to upgrade their project to build from our latest version.

In the mean time i have provided you with a set of `.rpm` files, which i build from this GIthub repository, that you can apply manually on your system to upgrade to the latest v3.52.16 release.
