### ISSUE TITLE
Question: how to connect Debian 12 with iODBC to Azuresql 

### ISSUE THREAD

**Issue by olsonnn** [openlink/iODBC#95]
Debian 12.2
For Freeradius 3.2.3 used with iodbc module:

Connect seems to got stuck in Freeradius 

Not sure if tells me there IS a connect or still connecting.
Any help or tools required for troubleshooting would be cool...
iodbctest  with mssql dsn returns nothing either.

From debug:
############################################

** iODBC Trace file
** Trace started on Fri Dec 08 10:13:52 2023
** Driver Manager: 03.52.0812.0326

[000000.000102]
freeradius      7FC26BC83280 ENTER SQLAllocEnv
                SQLHENV         * 0x565529910280

[000000.000112]
freeradius      7FC26BC83280 EXIT  SQLAllocEnv with return code 0 (SQL_SUCCESS)
                SQLHENV         * 0x565529910280 (0x56552962ad40)

[000000.000121]
freeradius      7FC26BC83280 ENTER SQLAllocConnect
                SQLHENV           0x56552962ad40
                SQLHDBC         * 0x565529910288

[000000.000131]
freeradius      7FC26BC83280 EXIT  SQLAllocConnect with return code 0 (SQL_SUCCESS)
                SQLHENV           0x56552962ad40
                SQLHDBC         * 0x565529910288 (0x5655299104f0)

[000000.000142]
freeradius      7FC26BC83280 ENTER SQLConnect
                SQLHDBC           0x5655299104f0
                SQLCHAR         * 0x5655298dae70
                                  | mssql                                    |
                SQLSMALLINT       -3 (SQL_NTS)
                SQLCHAR         * 0x5655298daee0
                                  | Usr1                                    |
                SQLSMALLINT       -3 (SQL_NTS)
                SQLCHAR         * 0x7fc26b1375d0
                                  | ****                                     |
                SQLSMALLINT       -3 (SQL_NTS)

############################################

my /etc/odbc.ini
[mssql]
Description = AAA db server
Driver = iodbc
Server = myserver.database.windows.net
port = 1433
Database = mydatabase

[ODBC]
Trace = 1
TraceFile = /tmp/odbctrace.log
Debug = 1
DebugFile = /tmp/odbcdebug.log

my /etc/odbcinst.ini
[iodbc]
Description=test
Driver=/usr/lib/x86_64-linux-gnu/libiodbc.so.2

**Comment by HughWilliams** [comment]
In the `odbcinst.ini` file you have the entry `Driver=/usr/lib/x86_64-linux-gnu/libiodbc.so.2`  which is incorrect as `libiodbc.so.2` which is the iODBC Driver Manager library which you are this connect back to itself ending in a loop which is probably why the SQLConnect call is hung in loop.

It is indicated the connection is being sought to `Azuresql` for which an [Azure SQL ODBC Driver](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=alpine18-install%2Calpine17-install%2Cdebian8-install%2Credhat7-13-install%2Crhel7-offline) is required and is what the `Driver` param should being referencing to enable a connection to be made to such a database.

**Comment by olsonnn** [comment]
thanks @HughWilliams ! Installed the Azure SQL odbc driver and changed it. 1 step further: but it seems im still missing something :(

/usr/lib/freeradius# iodbctest "DSN=mssql;UID=myUsr;PWD=mypass"
iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.0812.0326
1: SQLDriverConnect = ????????????????????????? (0) SQLSTATE=
2: SQLDriverConnect = ??????????????????????????????????? (0) SQLSTATE=
1: ODBC_Connect = ???????????????????????????? (0) SQLSTATE=
2: ODBC_Connect = ???????????????????????????????????     (0) SQLSTATE=


Debug now says from Freeradius

[000000.000181]
freeradius      7F54F708B280 ENTER SQLConnect
                SQLHDBC           0x55bb2e5eb330
                SQLCHAR         * 0x55bb2e5b5e70
                                  | mssql                                    |
                SQLSMALLINT       -3 (SQL_NTS)
                SQLCHAR         * 0x55bb2e5b5ee0
                                  | UsrSBR                                   |
                SQLSMALLINT       -3 (SQL_NTS)
                SQLCHAR         * 0x7f54f656b5d0
                                  | ****                                     |
                SQLSMALLINT       -3 (SQL_NTS)

[000016.831705]
freeradius      7F54F708B280 EXIT  SQLConnect with return code -1 (SQL_ERROR)
                SQLHDBC           0x55bb2e5eb330
                SQLCHAR         * 0x55bb2e5b5e70
                SQLSMALLINT       -3 (SQL_NTS)
                SQLCHAR         * 0x55bb2e5b5ee0
                SQLSMALLINT       -3 (SQL_NTS)
                SQLCHAR         * 0x7f54f656b5d0
                SQLSMALLINT       -3 (SQL_NTS)

[000016.831796]
freeradius      7F54F708B280 ENTER SQLError
                SQLHENV           0x55bb2e305d40
                SQLHDBC           0x55bb2e5eb330
                SQLHSTMT          0x0 (SQL_NULL_HANDLE)
                SQLCHAR         * 0x7fffafd02370
                SQLINTEGER      * 0x7fffafd0236c
                SQLCHAR         * 0x7fffafd02470
                SQLSMALLINT       256
                SQLSMALLINT     * 0x7fffafd0236a

**Comment by HughWilliams** [comment]
What are the instructions used for setting up your Freeradius 3.2.3 application ? 

Where did you obtain the iODBC Driver Manager from as the indicated version of 03.52.0812.0326 is from 2012 and would not work with the latest unicode drivers, hence the `???...` chars displayed on connect ? And requires an update to the latest iODBC Driver Manager version [03.52.1623.0502](https://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/ChangeNotes#2023-05-02%20-%20iODBC%20Stable%20Version%203.52.16%20Released), which supports the different variants (UCS2/UCS4) of unicode ODBC drivers.

**Comment by olsonnn** [comment]
@HughWilliams 
Install from here: https://networkradius.com/packages/#fr32-debian-bookworm
Then apt install freeradius freeradius-utils freeradius-iodbc

But it seems the old iODBC Driver Manager is fooling me...  
https://packages.debian.org/bookworm/iodbc

Under investigation.
Great help already... thanks

**Comment by olsonnn** [comment]
Even with the new version got same results on debian 12 with iodbctest

iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.1623.0502
1: SQLDriverConnect = ???????????????????????????? (0) SQLSTATE=?
2: SQLDriverConnect = ??????????????????????????????????????? (0) SQLSTATE=?
1: ODBC_Connect = ???????????????????????????? (0) SQLSTATE=?
2: ODBC_Connect = ??????????????????????????????????????? (0) SQLSTATE=?

something is still missing :(

**Comment by HughWilliams** [comment]
Try setting the DSN attribute `DriverUnicodeType = UTF16` for the ODBC DSN you are seeking to make the connection with to tell the iODBC Driver Manager to use `UFT16` which is probably the driver unicode type used, rather than the iODBC default of `UCS4`.
